### ISSUE TITLE
Upgrade ESLint to v4

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/eslint-config-fluct#83]
http://eslint.org/blog/2017/06/eslint-v4.0.0-released

## Work Items

- [x] http://eslint.org/blog/2017/04/eslint-v4.0.0-alpha.0-released
    - [x] no-buffer-constructor
    - [x] ~[indent-legacy](http://eslint.org/docs/4.0.0/rules/indent-legacy)~
        - We don't include it as a part of this config.
- [x] http://eslint.org/blog/2017/04/eslint-v4.0.0-alpha.1-released
    - [x] array-bracket-newline
    - [x] Add consistent option to object-curly-newline
- [x] http://eslint.org/blog/2017/05/eslint-v4.0.0-alpha.2-released
- [x] http://eslint.org/blog/2017/05/eslint-v4.0.0-beta.0-released
    - [x] Add semi-style
    - [x] Add padding-line-between-statements
    - [x] Add for-direction
    - [x] Add switch-colon-spacing
    - [x] Remove deprecated rules
        - [x] lines-around-directive
        - [x] newline-after-var
        - [x] newline-before-return
- [x] http://eslint.org/blog/2017/06/eslint-v4.0.0-rc.0-released
    - [x] array-element-newline
- [x] http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0
    - ~New rules have been added to eslint:recommended~
    - ~The indent rule is more strict~
    - ~Unrecognized properties in config files now cause a fatal error~
    - ~.eslintignore patterns are now resolved from the location of the file~
    - ~The padded-blocks rule is more strict by default~
    - ~The space-before-function-paren rule is more strict by default~
    - ~The no-multi-spaces rule is more strict by default~
    - ~References to scoped plugins in config files are now required to include the scope~

**Comment by saneyuki** [comment]
http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0
